### ISSUE TITLE
azurepipelines mistakenly labeled wily

### ISSUE THREAD

**Issue by rahulporuri** [tonybaloney/tonybaloney.github.io#2]
https://github.com/tonybaloney/tonybaloney.github.io/blob/e2547c6ab404c137cb9f02d1900e446cf541e9cf/index.html#L130-L144

**Comment by rahulporuri** [comment]
_on a side note, interesting talk at PyCon US 19_

**Comment by tonybaloney** [comment]
resolved. thanks
